pipeline{
    agent any 
    tools{
     maven 'M2_HOME' 
    }
    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube'){
                sh'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=koffimichel_geo-app1'
                }
                
            }
        }
        stage('maven'){
            steps{
            sh'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:APHKcPC3a5vmZR9FV9hqX6v1qo -T \
                target/bio*.jar \
                 "http://ec2-35-153-33-93.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
        stage('docker login'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | docker \
                login --username AWS --password-stdin 352415517565.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
        stage('docker image build'){
            steps{
                sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
            }
        }
        stage('image tagging'){
            steps{
                sh 'docker tag utc-app-dev:latest 352415517565.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                sh 'docker tag utc-app-dev:latest 352415517565.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.$BUILD_ID'
            }
        }
        stage('push image'){
            steps{
                sh 'docker push 352415517565.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                sh 'docker push 352415517565.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
           }
        }
    }
}