pipeline{
    agent any 
    tools{
        maven'M2_HOME'
    }
    stages{
        stage('maven1'){
            steps{
            sh'maven clean validate compile install test package'
            }
        }
    }
}